/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_PuckService */

#ifndef _Included_org_opensearch_knn_jni_PuckService
#define _Included_org_opensearch_knn_jni_PuckService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    initLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_PuckService_initLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    createIndex
 * Signature: ([IJILorg/opensearch/knn/index/store/IndexOutputWithBuffer;Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_PuckService_createIndex
  (JNIEnv *, jclass, jintArray, jlong, jint, jobject, jobject);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    initIndex
 * Signature: (JILjava/util/Map;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_PuckService_initIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    trainIndex
 * Signature: (Ljava/util/Map;IJ)[B
 *
 * Train a Puck index with training vectors (matches FAISS API)
 * Parameters: indexParameters (Map), dimension (int), trainVectorsPointer (long)
 * Returns: byte array containing trained model
 */
JNIEXPORT jbyteArray JNICALL Java_org_opensearch_knn_jni_PuckService_trainIndex
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    queryIndex
 * Signature: (J[FILjava/util/Map;)[Lorg/opensearch/knn/index/query/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensearch_knn_jni_PuckService_queryIndex
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jobject);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    loadIndexWithStream
 * Signature: (Lorg/opensearch/knn/index/store/IndexInputWithBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_PuckService_loadIndexWithStream
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    loadBinaryIndex
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_PuckService_loadBinaryIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    loadBinaryIndexWithStream
 * Signature: (Lorg/opensearch/knn/index/store/IndexInputWithBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_PuckService_loadBinaryIndexWithStream
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    loadIndex
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_PuckService_loadIndex
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    freeIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_PuckService_freeIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opensearch_knn_jni_PuckService
 * Method:    createIndexFromTemplate
 * Signature: ([IJILorg/opensearch/knn/index/store/IndexOutputWithBuffer;[BLjava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_PuckService_createIndexFromTemplate
  (JNIEnv *, jclass, jintArray, jlong, jint, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
